/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ContactForm } from "./ContactForm";
import { ContactFormCountArgs } from "./ContactFormCountArgs";
import { ContactFormFindManyArgs } from "./ContactFormFindManyArgs";
import { ContactFormFindUniqueArgs } from "./ContactFormFindUniqueArgs";
import { CreateContactFormArgs } from "./CreateContactFormArgs";
import { UpdateContactFormArgs } from "./UpdateContactFormArgs";
import { DeleteContactFormArgs } from "./DeleteContactFormArgs";
import { ContactFormService } from "../contactForm.service";
@graphql.Resolver(() => ContactForm)
export class ContactFormResolverBase {
  constructor(protected readonly service: ContactFormService) {}

  async _contactFormsMeta(
    @graphql.Args() args: ContactFormCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ContactForm])
  async contactForms(
    @graphql.Args() args: ContactFormFindManyArgs
  ): Promise<ContactForm[]> {
    return this.service.contactForms(args);
  }

  @graphql.Query(() => ContactForm, { nullable: true })
  async contactForm(
    @graphql.Args() args: ContactFormFindUniqueArgs
  ): Promise<ContactForm | null> {
    const result = await this.service.contactForm(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ContactForm)
  async createContactForm(
    @graphql.Args() args: CreateContactFormArgs
  ): Promise<ContactForm> {
    return await this.service.createContactForm({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => ContactForm)
  async updateContactForm(
    @graphql.Args() args: UpdateContactFormArgs
  ): Promise<ContactForm | null> {
    try {
      return await this.service.updateContactForm({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ContactForm)
  async deleteContactForm(
    @graphql.Args() args: DeleteContactFormArgs
  ): Promise<ContactForm | null> {
    try {
      return await this.service.deleteContactForm(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
