/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ServiceAreaService } from "../serviceArea.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ServiceAreaCreateInput } from "./ServiceAreaCreateInput";
import { ServiceArea } from "./ServiceArea";
import { ServiceAreaFindManyArgs } from "./ServiceAreaFindManyArgs";
import { ServiceAreaWhereUniqueInput } from "./ServiceAreaWhereUniqueInput";
import { ServiceAreaUpdateInput } from "./ServiceAreaUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ServiceAreaControllerBase {
  constructor(
    protected readonly service: ServiceAreaService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ServiceArea })
  @nestAccessControl.UseRoles({
    resource: "ServiceArea",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createServiceArea(
    @common.Body() data: ServiceAreaCreateInput
  ): Promise<ServiceArea> {
    return await this.service.createServiceArea({
      data: data,
      select: {
        areaName: true,
        areaZipCode: true,
        createdAt: true,
        id: true,
        mapUrl: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ServiceArea] })
  @ApiNestedQuery(ServiceAreaFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ServiceArea",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async serviceAreas(@common.Req() request: Request): Promise<ServiceArea[]> {
    const args = plainToClass(ServiceAreaFindManyArgs, request.query);
    return this.service.serviceAreas({
      ...args,
      select: {
        areaName: true,
        areaZipCode: true,
        createdAt: true,
        id: true,
        mapUrl: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ServiceArea })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServiceArea",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async serviceArea(
    @common.Param() params: ServiceAreaWhereUniqueInput
  ): Promise<ServiceArea | null> {
    const result = await this.service.serviceArea({
      where: params,
      select: {
        areaName: true,
        areaZipCode: true,
        createdAt: true,
        id: true,
        mapUrl: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ServiceArea })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServiceArea",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateServiceArea(
    @common.Param() params: ServiceAreaWhereUniqueInput,
    @common.Body() data: ServiceAreaUpdateInput
  ): Promise<ServiceArea | null> {
    try {
      return await this.service.updateServiceArea({
        where: params,
        data: data,
        select: {
          areaName: true,
          areaZipCode: true,
          createdAt: true,
          id: true,
          mapUrl: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ServiceArea })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ServiceArea",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteServiceArea(
    @common.Param() params: ServiceAreaWhereUniqueInput
  ): Promise<ServiceArea | null> {
    try {
      return await this.service.deleteServiceArea({
        where: params,
        select: {
          areaName: true,
          areaZipCode: true,
          createdAt: true,
          id: true,
          mapUrl: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
